open! Ctypes

(* This Types_generated module is an instantiation of the Types
   functor defined in the type_description.ml file. It's generated by
   a C program that Dune creates and runs behind the scenes. *)
module Types = Types_generated

module Functions (F : Ctypes.FOREIGN) = struct
  open! F

  let libbpf_major_version =
    foreign "libbpf_major_version" (void @-> returning uint32_t)
  let libbpf_minor_version =
    foreign "libbpf_minor_version" (void @-> returning uint32_t)
end
