open! Ctypes

(* This Types_generated module is an instantiation of the Types
   functor defined in the type_description.ml file. It's generated by
   a C program that Dune creates and runs behind the scenes. *)
module Types = Types_generated

module Functions (F : Ctypes.FOREIGN) = struct
  open F

  let libbpf_major_version =
    foreign "libbpf_major_version" (void @-> returning uint32_t)

  let libbpf_minor_version =
    foreign "libbpf_minor_version" (void @-> returning uint32_t)

  let libbpf_strerror =
    foreign "libbpf_strerror" (int @-> ptr char @-> size_t @-> returning int)

  [@@alert unsafe "does not support flag set"]
  let libbpf_set_strict_mode =
      foreign "libbpf_set_strict_mode" (Types.enum_libbpf_strict_mode @-> returning void)

  [@@alert unsafe "incomplete implementation"]
  let libbpf_bpf_attach_type_str =
    foreign "libbpf_bpf_attach_type_str" (Types.bpf_attach_type @-> returning string)

  let bpf_object__open =
    foreign "bpf_object__open" (string @-> returning (ptr_opt Types.bpf_object))

  let bpf_object__load =
    foreign "bpf_object__load" (ptr Types.bpf_object @-> returning int)
end
